spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secretKey: fastCatch8jo
  accessTokenValidTime: 86400000
  refreshTokenValidTime: 604800000
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/MiniProject?createDatabaseIfNotExist=true&useSSL=true
#    username: root
#    password: root1234!!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true