POST http://localhost:8080/api/accommodations
Content-Type: application/json

{
  "name": "데미샘바우펜션",
  "category": "PENSION",
  "region": "HONAM",
  "phoneNumber": "063-433-4978",
  "address": "전라북도 진안군 백운면 백장로 407",
  "latitude": 35.6613392033,
  "longitude": 127.4212859669,
  "description": "데미샘바우펜션은 마이산이 한눈에 올려다보이는 풍광 좋은 곳으로 섬진강의 발원지인 데미샘에 자리 잡고 있다. 바로 앞에는 물놀이하기 딱 좋은 백운동이 흐르는 것도 장점 중의 하나로 펜션 안에 커다란 바위가 있어 큰바위펜션이라 이름 지어졌다. 펜션 주위로 우뚝우뚝 솟은 녹색의 봉우리가 아름답고 조용한 곳이다. 한 채씩 단독으로 지어진 객실 또한 이곳만이 가진 특징으로 7개의 객실은 통나무로 지어져 실내에 들어서면 나무 향기가 난다. 이곳에서는 바베큐, 불멍을 할 수 있으며 잘 꾸며진 정원에는 정자도 있다. ",
  "image": "pension_21.jpeg"
}