POST http://localhost:8080/api/accommodations/1
Content-Type: application/json

[
  {
    "name" : "스탠다드 룸",
    "price" : 45000,
    "baseHeadCount": 2,
    "maxHeadCount": 4,
    "description": "기본적인 방으로 편안한 휴식을 제공합니다.",
    "checkInTime": "15:00",
    "checkOutTime": "12:00"
  },
  {
    "name" : "스댄다드 디럭스 룸",
    "price" : 55000,
    "baseHeadCount": 2,
    "maxHeadCount": 4,
    "description": "디럭스 침대로 편안한 휴식을 제공합니다.",
    "checkInTime": "15:00",
    "checkOutTime": "12:00"
  },
  {
    "name" : "럭셔리 룸",
    "price" : 85000,
    "baseHeadCount": 2,
    "maxHeadCount": 6,
    "description": "큰 방과 두개의 디럭스 침대로 편안한 휴식을 제공합니다.",
    "checkInTime": "15:00",
    "checkOutTime": "12:00"
  }
]
